openapi: 3.0.0

info:
  title: Goal Bet API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1

paths:
  /info:
    get:
      summary: Return the info.
      operationId: getInfo
      responses:
        '200':
          description: return the info
          content:
            application/json:
              schema: 
                type: string
  /getUserDetails:
    get:
      summary: Returns a list of users data.
      operationId: getUserDetails
      responses:
        '200':
          description: A JSON array of user data
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/UserData'
  /predictGoal:
    post:
      summary: Add goal
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictionDetails'
      responses:
        '200':
          description: A JSON array of user data
          content:
            application/json:
              schema: 
                type: string
                
  /getPredictions:
    get:
      summary: Returns a list of users data.
      operationId: getPredictions
      responses:
        '200':
          description: A JSON array of user data
          content:
            application/json:
              schema: 
                type: string
                  
components:
  schemas:
  
    PredictionDetails:
      properties:
        matchId:
          type: integer
        userId:
          type: integer
        teamGoals1:
          type: integer          
        teamGoals2:
          type: integer 
        
    UserData:
      properties:
        id:
          type: integer
        name:
          type: string
      # Both properties are required
      required:  
        - id
        - name